apiVersion: apps/v1
kind: Deployment
metadata:
  name: braintaskk
spec:
  replicas: 2
  selector:
    matchLabels:
      app: braintaskk
  template:
    metadata:
      labels:
        app: braintaskk
    spec:
      containers:
      - name: braintaskk
        image: 806700449883.dkr.ecr.us-east-1.amazonaws.com/braintask:latest
        ports:
        - containerPort: 80
