apiVersion: apps/v1
kind: Deployment
metadata:
  name: braintask
spec:
  replicas: 1
  selector:
    matchLabels:
      app: braintask
  template:
    metadata:
      labels:
        app: braintask
    spec:
      containers:
      - name: braintask
        image: 906865226128.dkr.ecr.us-east-1.amazonaws.com/braintask
        ports:
        - containerPort: 80
